### PR TITLE
Add a setter for the client name

### PR DESCRIPTION
**Pull request by duncte123**

### CODE REVIEW

**Comment by Frederikam** [comment]
Why? The client name is Lavalink-Client

**Comment by duncte123** [comment]
Actually, it's set to "Client-Name"
And this change is because there are probably people like me who have different bots connected to lavalink wanting to use different client names for each bot

**Comment by Frederikam** [comment]
That's a typo. I think your problem could be solved by logging the bot ID on the server

**Comment by duncte123** [comment]
Fair enough

**Pull request closed without merging**
