### PR TITLE
Add rotation and distortion filters

### PR DESCRIPTION
**Pull request by TopiSenpai**

### CODE REVIEW

**Comment by TopiSenpai** [comment]
is there any need for bound checks?

**Comment by Frederikam** [comment]
Would be nice

Also you misspelled distortion 20 times

**Comment by TopiSenpai** [comment]
do you know the min & max bounds for those effects?
couldn't find it anywhere

**Comment by Frederikam** [comment]
No. Maybe check lavadsp

**Comment by TopiSenpai** [comment]
I did before asking and couldn't find any 
https://github.com/natanbc/lavadsp/blob/master/src/main/java/com/github/natanbc/lavadsp/rotation/RotationPcmAudioFilter.java
https://github.com/natanbc/lavadsp/blob/master/src/main/java/com/github/natanbc/lavadsp/distortion/DistortionPcmAudioFilter.java

**Review by Frederikam — APPROVED** [review]

**Comment by TopiSenpai** [comment]
Bump 👀

**Comment by Frederikam** [comment]
I thought this was merged. Stupid brain.

**Pull request merged**
